apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-finops-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-finops
  template:
    metadata:
      labels:
        app: demo-finops
    spec:
      containers:
      - name: web
        image: nginx:alpine
        resources:
          requests:
            cpu: "100m"     # Au lieu de 2000m
            memory: "128Mi" # Au lieu de 2Gi