apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-finops-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-finops
  template:
    metadata:
      labels:
        app: demo-finops
    spec:
      containers:
      - name: web
        image: nginx:alpine
        resources:
          requests:
            cpu: "2000m"     # Réservation massive : 2 vCPU
            memory: "2Gi"    # Réservation massive : 2 Go de RAM