apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: opencost
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: flux-system
  values:
    opencost:
      prometheus:
        internal: 
          url: prometheus-kube-prometheus-prometheus
          namespace: default
          port: 9090