apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opencost
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: opencost
      sourceRef:
        kind: HelmRepository
        name: opencost
        namespace: flux-system
  values:
    opencost:
      prometheus:
        internal: 
          serviceName: prometheus-kube-prometheus-prometheus
          namespaceName: default
          port: 9090
         
# 2. Configuration FinOps OpenCost (Niveau racine)

      opencost:
        customPricing:
          enabled: true
          # C'est ce bloc qui force l'écrasement des prix AWS par les tiens
          costModel:
            description: "Tarifs OVHcloud"
            currencyCode: "EUR"
            cpu: "0.015"
            ram: "0.005"
            storage: "0.0002"